# merge with providerd
title: ZoeAPP
description: A starter template for zoe app.
url: https://labs.zoe.im/zoe-app
logo: images/logo-512x512.png # https://via.placeholder.com/120x60/E53E3E.png/fff
lang: zh-CN

# display in the right of the logo
version: beta

author:
  name: Zoe
  email: hi@zoe.im
  homepage: 'https://zoe.im'
  # TODO: or use _zoe: Object
  avatar: zoe(sharp=true)https://avatars1.githubusercontent.com/u/2942042?s=200
  minibio: 知行合一

organization:
  name: ${zoe.title}
  url: ${zoe.url}
  logo: ${zoe.logo}

copyright:
  # content: © ZoeAPP - All rights reserved. Made with ❤️ by Zoe 
  holder: Zoe # take value from organization - author
  location: Hangzhou

links:
- title: Home
  category: Company
  href: /
- title: About
  category: Company
  href: /about
- title: Blog
  category: Company
  href: /blog
- title: Rust
  category: Products
  href: /rust
- title: More >>>
  category: Products
  href: /products
- title: Golang
  category: Services
  href: /golang
- title: More >>>
  category: Services
  href: /projects

navs:
- title: Home
  href: /
- title: About
  href: /about
- title: Services
  href: /services
  items:
  - title: Golang turorials
    href: /services/golang
  - title: Frontend from zero
    href: /services/frontend
- title: Blog
  href: /blog

# social links with icons
socials:
  email: 'hi@zoe.im'
  github: 'zoeim'
  twitter: 'jiusanzhou'
  facebook: 'jiusanzhou'
  telegram: 'jiusanzhou'
  linkedin: 'johnzoe'

# theme for global
primaryColor: 'purple' #663399 # tomato how to change to colorSchema

# layouts configuration
layouts:
  default:
    maxWidth: 70rem
    header:
      logoProps:
        textColor: 'unset'
    footer:
      disableBorder: true
      disableGotop: false
      disableLogo: false
      disableSocials: false
      disableLinks: false

features:
- title: Performance built-in
  description: |
    Gatsby automates code splitting, image optimization, inlining critical styles,
    lazy-loading, prefetching resources, and more to ensure your site is fully optimized.
    **No manual tuning required.**
- title: Scalability — affordable and instant 
  description: |
    Gatsby sites don't require complex scaling operations or expensive hosting.
    They scale when needed, but when traffic drops so does your usage — and your costs.
    **Host at scale for pennies.**
- title: Security by default
  description: |
    Gatsby’s serverless rendering generates static HTML at build time.
    No server and no reachable database equals no malicious requests, DDOS attacks, or accidental exposure.
    **A Gatsby site’s attack surface is nonexistent.**
- title: Accessibility by design
  description: |
    Recognized by WebAIM as the most accessible web framework, we build in best practices like accessible routing,
    progressive page enhancement and a built-in linting tool to find accessibility errors.
    **Help make the web work for everyone.**

# elements register elements
elements:
  hero:

# views, auto load from src/views, views
views:
  hero: 

# pages, auto laod from src/pages
pages:
  index:
    layout: default
    children:
    - hero: null # from zoe.views or src/views, ./hero.jsx
    - src/components/section:
        title: ZoeAPP
        subTitle:
          type: logo
        description: | 
          Create your app landing page without code.
          Static websites and Progressive Web Applications are secure, scalable, SEO-friendly, and even up to 10x faster.
        action: # this is a simple action or with type, with component? how do I know this is not a obejct props
          type: downloader-app # take a element
          provider: github # select a provider
          repo: moeapp/mtb-mobile
          itemPrefix: 'Download '
          hiddenUnsupported: true
          justify: flex-start
          itemProps:
            colorScheme: red
    - section: # section is a global views called section
        children: # generate from features

# for app release, we need to add github release source
releaseRepo:
- moeapp/mtb-mobile
- strapi/strapi

# temp for hero
hero:
  title: ZoeAPP
  subTitle:
    type: IconButton
    isRound: true
    icon:
      type: SunIcon
  description:
    children:
    - type: Markdown
      source: |
        Create your app landing page ~~without code~~.
        
        Static websites and Progressive Web Applications are **secure**, **scalable**, **SEO-friendly**, and even up to **10x faster**.
  action: # this is a simple action or with type
    type: AppRelease # take a action type
    provider: github # select a provider
    repo: moeapp/mtb-mobile
    itemPrefix: 'Download '
    justify: [center, center, flex-start, flex-start]
    # hiddenUnsupported: false
    # itemProps:
    #   colorScheme: ${zoe.primaryColor}
  children:
    type: Center
    mr: ['0', '0', 5rem, 5rem]
    children:
      type: ViewLogo
      minimal: true
      clickable: false
      imageProps:
        w: [5rem, 10rem, 15rem, 15rem]
        rounded: [1rem, 1rem, 2rem, 2rem]
  position: right
  minH: calc(100vh - 20rem)
  # theme: grey
  # rounded: 2rem
  mt: 1rem

# extend for app landing page

# previews

# reviews

# how to define an element???

# we need to merge zoefile and zoefile

# auto load .md for something else in current directory

googleAnalyticsTrackingId: 'xxxxxxx'

# can register a component

# important and just modify by template
# because we need to install node package
# but if we can install it with config
# we can add one

plugins:
- gatsby-source-filesystem:
    name: default
    path: ${__dirname} # default load all files in current directory
    ignore: ["**/public/**", "**/.cache/**", "**/.git/**", "**/.svn/**"] # important if we use project root path

- gatsby-plugin-google-analytics:
    # TODO: extrac all fonts from siteMeta
    trackingId: ${zoe.googleAnalyticsTrackingId}
    respectDNT: true

# - gatsby-plugin-web-font-loader:
#     google:
#       families: ['Poppins', 'Recoleta', 'Fredoka One', 'Cabin', 'Open Sans']

- gatsby-plugin-manifest:
    name: ${zoe.title}
    short_name: ${zoe.title}
    start_url: /
    background_color: ${zoe.primaryColor}
    theme_color: ${zoe.primaryColor}
    display: minimal-ui
    icon: ${zoe.logo}

- gatsby-plugin-chakra-ui:
    isResettingCSS: true
    isUsingColorMode: false

# auto create remoteImageNode from siteMeta
# TODO: auto register this plugin
- gatsby-plugin-remote-images:
    nodeType: 'RemoteImage' # default node name when we create
    imagePath: '.url'

- gatsby-plugin-react-helmet
- gatsby-plugin-sharp
- gatsby-transformer-sharp
- gatsby-plugin-offline