# merge with providerd
title: ZoeAPP
description: A starter template for zoe app.
url: https://labs.zoe.im/gatsby-starter-zoe-app
logo: images/logo-512x512.png # https://via.placeholder.com/120x60/E53E3E.png/fff
lang: zh-CN

# display in the right of the logo
version: alpha

author:
  name: Zoe
  email: hi@zoe.im
  homepage: 'https://zoe.im'
  # TODO: or use _zoe: Object
  avatar: https://github.com/jiusanzhou.png # zoe(sharp=true)
  minibio: 知行合一，不将有限的生命献给无知、平庸和低俗。 
  github: 'zoeim'
  twitter: 'jiusanzhou'
  facebook: 'jiusanzhou'
  telegram: 'jiusanzhou'
  linkedin: 'johnzoe'
  wechat: https://cdn.jsdelivr.net/gh/jiusanzhou/jiusanzhou.github.io@archived/static/WeChat-JohnCx.jpeg

organization:
  name: ${zoe.title}
  url: ${zoe.url}
  logo: ${zoe.logo}

copyright:
  from: 2011
  # content: © ZoeAPP - All rights reserved. Made with ❤️ by Zoe 
  holder: Zoe # take value from organization - author
  location: Hangzhou

# footer links
links:
- title: Home
  category: Company
  href: /
- title: About
  category: Company
  href: /about
- title: Blog
  category: Company
  href: /blogs
- title: Help Center
  category: Plugins
  href: /help
- title: App landing
  category: Plugins
  href: /app-landing
- title: Projects
  category: Open Source
  href: /projects

# nav links
navs:
- title: Products
  href: /products
  items:
  - title: KubeDB
    description: Run production-grade Database on Kubernetes
    href: https://kubedb.com/
    # icon: https://appscode.com/assets/images/products/kubedb/kubedb-icon.png
    color: blue # ignore this?
  - title: Stash
    description: Backup your Kubernetes Stateful APplications
    href: https://stash.run/
    # icon: https://appscode.com/assets/images/products/stash/stash-icon.png
  - title: KubeVault
    description: Tools for running HashiCorp Vault on Kubernetes
    href: https://kubevault.com/
    # icon: https://appscode.com/assets/images/products/kubevault/kubevault-icon.png
  - title: Kubeform
    description: Provision cloud resources using Kubernetes CRDs & Terraform
    href: https://kubeform.com/
    # icon: https://appscode.com/assets/images/products/kubeform/kubeform-icon.png
- title: Open Source
  href: /open-source/
  items:
  - title: Voyager
    description: Secure HAProxy Ingress Controller for Kubernetes
    href: https://voyagermesh.com/
    # icon: https://appscode.com/assets/images/products/voyager/voyager-icon.png
  - title: Guard
    description: Kubernetes Authentication WebHook Server
    href: https://appscode.com/products/guard/
    # icon: https://appscode.com/assets/images/products/guard/guard-icon.png
  - title: Kubed
    description: Kubernetes cluster manager daemon
    href: https://appscode.com/products/kubed/
    # icon: https://appscode.com/assets/images/products/kubed/kubed-icon.png
  - title: Pharmer
    description: Kubernetes Cluster Manager using Kubeadm & Cluster API
    href: https://pharmer.cloud/
    # icon: https://appscode.com/assets/images/products/pharmer/pharmer-icon.png
  - title: Swift
    description: Ajax friendly Helm Tiller Proxy
    href: https://appscode.com/products/swift/
    # icon: https://appscode.com/assets/images/products/swift/swift-icon.png
  - title: Searchlight
    description: Alerts for Kubernetes
    href: https://appscode.com/products/searchlight/
    # icon: https://appscode.com/assets/images/products/searchlight/searchlight-icon.png
- title: Plugins
  items:
  - title: Help Center
    href: /help
  - title: App Landing
    href: /app-landing
- title: Blog
  href: /blogs
- title: About
  href: /about

# social links with icons
socials:
  email: 'hi@zoe.im'
  github: 'zoeim'
  twitter: 'jiusanzhou'
  facebook: 'jiusanzhou'
  telegram: 'jiusanzhou'
  linkedin: 'johnzoe'

# theme for global
primaryColor: 'purple' #663399 # tomato how to change to colorSchema

# section should take this
maxWidth: ["100%", "80%", "80%", "80%", "60rem"]

# layouts configuration
layouts:
  default:
    maxWidth: ["100%", "80%", "80%", "80%", "60rem"]
    header:
      logoProps:
        textColor: 'unset'
    footer:
      disableBorder: true
      disableGotop: false
      disableLogo: false
      disableSocials: false
      disableLinks: false
      logoProps:
        textColor: 'unset'

# TODO: elements register elements
elements:
  hero:

# TODO: views, auto load from src/views, views
views:
  hero: 

# pages, auto laod from src/pages
pages:
  /app-landing: pages/app-page.yaml # pages/index.json, index.jsx
  # /about: ./content/about.md

# for app release, we need to add github release source
# appReleases
releases:
- provider: github
  repo: moeapp/automate


# projects for labs projects
# repoProjects
projects:
- provider: github
  owners:
  - jiusanzhou
  tag: zoe-lab

# Help center, mostly for Q&A. This is not docs center
# labels: help:xx
# issues: help:
helpqa:
- provider: github
  repo: jiusanzhou/gatsby-starter-zoe-app
  labelPrefix: help # tag layout, use this as a category
  # _: ":"
  # source: issues??? can be other
  # state: OPEN?

# previews

# reviews

# how to define an element???

# we need to merge zoefile and zoefile

# auto load .md for something else in current directory

googleAnalyticsTrackingId: 'xxxxxxx'

# parse images from node
# TODO: Mdx: http[s]://.+?.jpeg
remoteImageNodes:
- type: Mdx
  field: rawBody
  patterns:
  - '!\[.*?\]\((.+?)[ \)]'
- type: Mdx
  field: frontmatter.banner
  patterns:
  - 'https?:\/\/.+'

# for current file.
remoteImageUrlPatterns: # must has :// as default
- avatars[0-9]?\.githubusercontent\.com
- \.png$
- \.jpeg$

pageWrappers:
- path: "*"
  match: "/[Mm]icro[Mm]essenger|[Aa]lipay/.test(navigator.userAgent)"
  component:
    type: WechatBrokenGuide


# turn mdx to common type
customNodes:
- name: MdxPage
  when:
    type: Mdx
    name: content/pages
- name: MdxPost
  when:
    type: Mdx
    name: content/posts

# for all pages?
basePath: /
pathPrefix: ${zoe.basePath}
# pageTemplate: 

# what about blogs basePath
basePathBlog: /blog
blogListTemplate: 
blogPageTemplate:

basePathHelp: /help

# TODO: path config move to each plugin config

# can register a component

# important and just modify by template
# because we need to install node package
# but if we can install it with config
# we can add one

# Comments system
comments:
  provider: giscus
  repo: jiusanzhou/jiusanzhou.github.io
  repoID: "MDEwOlJlcG9zaXRvcnkxMzQ2MDAzMDM="
  categoryID: "DIC_kwDOCAXWb84B-qn9"
  # category: Announcements
  theme: preferred_color_scheme

# plugins for custom
zoePlugins:
- src/plugins/app-release
- src/plugins/remote-image
- src/plugins/static-page
- src/plugins/custom-page
- src/plugins/repo-project
- src/plugins/blog-post
- src/plugins/issue-helpqa

# Gatsby plugins

plugins:
# auto add those 2 plugins
- gatsby-source-filesystem:
    name: content/posts
    path: ${__dirname}/content/posts
- gatsby-source-filesystem:
    name: content/pages
    path: ${__dirname}/content/pages

- gatsby-source-filesystem:
    name: default
    path: ${__dirname} # default load all files in current directory
    ignore: ["**/public/**", "**/.cache/**", "**/.git/**", "**/.svn/**"] # important if we use project root path

- gatsby-plugin-mdx:
    lessBabel: true
    extensions: [.mdx, .md]
    gatsbyRemarkPlugins:
    - gatsby-remark-images:
        maxWidth: 1200
    plugins:
    - gatsby-remark-images:
        maxWidth: 1200


- gatsby-plugin-google-analytics:
    # TODO: extrac all fonts from siteMeta
    trackingId: ${zoe.googleAnalyticsTrackingId}
    respectDNT: true

- gatsby-plugin-web-font-loader:
    google:
      families: ['Poppins', 'Recoleta', 'Fredoka One', 'Cabin', 'Open Sans']

- gatsby-plugin-manifest:
    name: ${zoe.title}
    short_name: ${zoe.title}
    start_url: /
    background_color: ${zoe.primaryColor}
    theme_color: ${zoe.primaryColor}
    display: minimal-ui
    icon: ${zoe.logo}

- "@chakra-ui/gatsby-plugin":
    resetCSS: true
    isUsingColorMode: true

# auto create remoteImageNode from siteMeta
# TODO: auto register this plugin
- gatsby-plugin-remote-images:
    nodeType: 'RemoteImage' # default node name when we create
    imagePath: 'url'

- gatsby-plugin-react-helmet
- gatsby-plugin-sharp
- gatsby-transformer-sharp
- gatsby-plugin-offline
- gatsby-plugin-image

# need options!!!
# how to register plugin from internal plugin in src/plugins
- gatsby-plugin-feed:
    query: |
      {
        site {
          siteMetadata {
            title
            description
            url
            site_url: url
            basePathBlog
          }
        }
      }
    feeds:
    - query: |
        {
          allMdxPost(
            sort: { order: DESC, fields: [createdTime] },
          ) {
            edges {
              node {
                excerpt
                description
                slug
                title
                html
              }
            }
          }
        }
      serialize: |
        ({ query: { site, allMdxPost } }) => {
          const { basePathBlog } = site.siteMetadata
          return allMdxPost.edges.map(edge => {
            return Object.assign({}, edge.node.frontmatter, {
              title: edge.node.title,
              description: edge.node.description || edge.node.excerpt,
              date: edge.node.createdTime,
              url: site.siteMetadata.url + basePathBlog + edge.node.slug,
              guid: site.siteMetadata.url + basePathBlog + edge.node.slug,
              custom_elements: [{ "content:encoded": edge.node.html }],
            })
          })
        }
      output: "/rss.xml"
      title: ${zoe.title} RSS Feed

# registered by some plugins
- gatsby-source-graphql:
    typeName: Github
    fieldName: github
    url: "https://api.github.com/graphql"
    headers:
      Authorization: Bearer ${process.env.GITHUB_TOKEN}
    

# - gatsby-transformer-remark:
#     plugins:
#     - resolve: gatsby-remark-images
#       options:
#         maxWidth: 590
- gatsby-transformer-remark:
    plugins:
    - gatsby-remark-images:
        maxWidth: 590